title: "A Blog on Data Analytics"
author: "Ali Arsalan Kazmi"
description: "A blog to give shape to my musing on Data Analytics"
#subheading: "Really cool blog about ... something"
more: "read more"
url: "http://aliarsalankazmi.github.io"
baseurl: "/contrast" # comment out if in root directory

comments:
    disqus: #"niklasbuschmann"
#    isso: "comments.mysite.org"

style:
#    body: "whitesmoke"
    padding: 33%
    anchor: "#46f"
    serif-heading: true
    nav: "#181818"
#    headline: "#06f"
    description: "white"
    article:
        odd: "#ffffff"
        even: "#222222"

links:
  - github: "https://github.com/aliarsalankazmi/"
  - twitter: "https://twitter.com/scac1041/"
  - linkedin: "https://ae.linkedin.com/in/aliarsalankazmi"
#  - google-plus: "https://plus.google.com/+me"
#  - reddit: "https://www.reddit.com/user/me/"
#  - youtube: "https://www.youtube.com/user/me"
#  - steam: "http://steamcommunity.com/id/me/"

paginate: 10
excerpt_separator: "\n\n\n" # excerpt ends after two blank lines
defaults: [{scope: {path: ""}, values: {layout: "default"}}, {scope: {path: "", type: "posts"}, values: {comments: true}}]
gems: [jekyll-feed] # include feed plugin (supported by gh-pages)
